[package]
name = "repo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.14", features = ["derive"] }
git2 = "0.18.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"

